// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDz7gw3Hs3APsn_dB_ihXRqyhC5DNKfS78',
    appId: '1:279740983075:web:b5b029c50dc9c96004ce96',
    messagingSenderId: '279740983075',
    projectId: 'semper-elections',
    authDomain: 'semper-elections.firebaseapp.com',
    storageBucket: 'semper-elections.appspot.com',
    measurementId: 'G-ZBL8NF32P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqLq1HYvIeUAWaQD0xLrxTK-CZzWqhBk',
    appId: '1:279740983075:android:aa9f2ca5bfec756204ce96',
    messagingSenderId: '279740983075',
    projectId: 'semper-elections',
    storageBucket: 'semper-elections.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpDRSFuxP183w12GRxuGefT7ohfmIJdGw',
    appId: '1:279740983075:ios:1ba1c877dde5854504ce96',
    messagingSenderId: '279740983075',
    projectId: 'semper-elections',
    storageBucket: 'semper-elections.appspot.com',
    iosClientId: '279740983075-je83b1rkaidr1tfvo4ra0kp1uj22rd69.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostels',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpDRSFuxP183w12GRxuGefT7ohfmIJdGw',
    appId: '1:279740983075:ios:a5c634a9fb0d376a04ce96',
    messagingSenderId: '279740983075',
    projectId: 'semper-elections',
    storageBucket: 'semper-elections.appspot.com',
    iosClientId: '279740983075-e1do52t8vqgaoe8m2o03kjqn9h3os1t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.hostels.RunnerTests',
  );
}
