// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0WgN0MUbSMjnzIdosj5DQwukhbTULWi4',
    appId: '1:901402058388:web:b67a4bdcdcd31a97c25e81',
    messagingSenderId: '901402058388',
    projectId: 'flutterfirebaseauth-1c71a',
    authDomain: 'flutterfirebaseauth-1c71a.firebaseapp.com',
    databaseURL: 'https://flutterfirebaseauth-1c71a.firebaseio.com',
    storageBucket: 'flutterfirebaseauth-1c71a.appspot.com',
    measurementId: 'G-6CP2W09NXS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAb8DdSAfTtrmacn7wLERHJA1O0PqEF0vQ',
    appId: '1:901402058388:android:2d1685cbe604814dc25e81',
    messagingSenderId: '901402058388',
    projectId: 'flutterfirebaseauth-1c71a',
    databaseURL: 'https://flutterfirebaseauth-1c71a.firebaseio.com',
    storageBucket: 'flutterfirebaseauth-1c71a.appspot.com',
  );
}
